name: takyam-bbs-vanilla
version: 0.0.1
description: BBS example which created by Dart use no framwork.
author: takyam <takayuki.yamaguch.m@gmail.com>
homepage: https://github.com/takyam-git/
documentation: https://github.com/takyam-git/vanilla-bbs
dependencies:
  http_server: ">=0.9.5+1 <0.10.0"
  route: ">=0.4.6 <0.5.0"
  mustache: ">=0.1.8 <0.2.0"
  path: ">=1.3.1 <2.0.0"
dev_dependencies:
  unittest: ">=0.11.4 <0.12.0"

